stages:
  - deploy_backend

deploy_backend:
  tags: ["deploy"]  
  stage: deploy_backend
  script:
    - ls
    - pwd
    - cd ..
    - cp -r backend/ /home/EUB/dshevche/Test
    - nginx-test 
    - nginx-restart
    - cd /home/EUB/dshevche/
    - rm -rf builds/
#nginx-restart  
  only:
    - main
#test2