stages:
  - deploy_backend

deploy_backend:
  tags: ["deploy"]
  stage: deploy_backend
  script:
    - |
      if docker service rm eu_payload; then
        echo "Service removed successfully."
      else
        echo "Service not found, continuing..."
      fi
    - rm -rf /home/EUB/dshevche/eu-bank/Test/backend/
    - cd ..
    - cp -r backend/ /home/EUB/dshevche/eu-bank/Test
    - echo "Successfully copied"
    - cd /home/EUB/dshevche/
    - rm -rf builds/
    - cd /home/EUB/dshevche/eu-bank
    - cp /home/EUB/dshevche/eu-bank/backend-main/.env /home/EUB/dshevche/eu-bank/Test/backend
    - docker stack deploy -c docker-compose.yml eu
    - docker service logs eu_payload
  only:
    - main

#Test4