stages:
  - deploy_backend

deploy_backend:
  tags: ["deploy"]
  stage: deploy_backend
  script:
    - |
      if docker service rm eu_payload; then
        echo "Service removed successfully."
      else
        echo "Service not found, continuing..."
      fi
    - sudo rm -rf /home/EUB/dshevche/eu-bank/Test/backend/
    - cd ..
    - cp -r backend/ /home/EUB/dshevche/eu-bank/Test
    - cd /home/EUB/dshevche/
    - sudo rm -rf builds/
    - cd /home/EUB/dshevche/eu-bank
    - docker service update --force eu_payload
    - nginx-test
    - nginx-restart
  only:
    - main
