stages:
  - test_backend
  # - deploy_backend

test_backend:
  stage: test_backend
  script:
    - ls
    - apt-get update -y
    - apt-get install -y ca-certificates curl expect coreutils
    - wget http://ftp.gnu.org/gnu/coreutils/coreutils-8.30.tar.xz
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - npm install --force
    - docker pull postgres:latest
    - |
      docker run -d \
        --name postgres_container \
        -e POSTGRES_USER=${PUSER} \
        -e POSTGRES_PASSWORD=${PPASS} \
        -e POSTGRES_DB=${PDB} \
        -p 5432:5432 \
        postgres:latest
    - sleep 15
    - echo "DATABASE_URI=postgres://${PUSER}:${PPASS}@db:5432/${PDB}" > .env
    - echo "PAYLOAD_SECRET=1ae76cdaf25a0813a977e4aa" >> .env
    - npm run dev
    - sleep 15
  only:
    - main

# deploy_backend:
#   tags: ['deploy']
#   stage: deploy_backend
#   before_script:
#     - git config --global http.postBuffer 524288000
#     - git fetch --depth=1000
#   script:
#     - |
#       if docker service rm eu_payload; then
#         echo "Service removed successfully."
#       else
#         echo "Service not found, continuing..."
#       fi
#     - rm -rf /home/EUB/dshevche/eu-bank/Test/backend/
#     - cd ..
#     - cp -r backend/ /home/EUB/dshevche/eu-bank/Test
#     - echo "Successfully copied"
#     - cd /home/EUB/dshevche/
#     - rm -rf builds/
#     - cd /home/EUB/dshevche/eu-bank
#     - cp /home/EUB/dshevche/eu-bank/backend-main/.env /home/EUB/dshevche/eu-bank/Test/backend
#     - docker stack deploy -c docker-compose.yml eu
#     - sleep 70
#     - docker service logs --raw eu_payload
#   only:
#     - main
#Test4
