stages:
  - deploy_backend

deploy_backend:
  tags: ["deploy"]  
  stage: deploy_backend
  script:
    - docker service rm eu_payload
    - rm -rf /home/EUB/dshevche/eu-bank/Test/backend/
    - cp -r backend/ /home/EUB/dshevche/eu-bank/Test
    - cd /home/EUB/dshevche/
    - rm -rf builds/
    - cd /home/EUB/dshevche/eu-bank
    - docker service update --force eu_payload
    - nginx-test
    - nginx-restart
  only:
    - main

