stages:
  - test_backend
#  - deploy_backend

test_backend:
  stage: test_backend
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache ca-certificates curl expect coreutils
    - wget http://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc
    - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable" | tee /etc/apt/sources.list.d/docker.list
    - apk update
    - apk add docker
    - service docker start
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apk add nodejs
    - npm install --force
    - docker pull postgres:latest
    - |
      docker run -d \
        --name postgres_container \
        -e POSTGRES_USER=${PUSER} \
        -e POSTGRES_PASSWORD=${PPASS} \
        -e POSTGRES_DB=${PDB} \
        -p 5432:5432 \
        postgres:latest
    - sleep 15
    - echo "DATABASE_URI=postgres://${PUSER}:${PPASS}@db:5432/${PDB}" > .env
    - echo "PAYLOAD_SECRET={$PAYLOAD_SECRET}" >> .env
    - npm run dev
    - sleep 15
  only:
    - main

# deploy_backend:
#   tags: ['deploy']
#   stage: deploy_backend
#   before_script:
#     - git config --global http.postBuffer 524288000
#     - git fetch --depth=1000
#   script:
#     - |
#       if docker service rm eu_payload; then
#         echo "Service removed successfully."
#       else
#         echo "Service not found, continuing..."
#       fi
#     - rm -rf /home/EUB/dshevche/eu-bank/Test/backend/
#     - cd ..
#     - cp -r backend/ /home/EUB/dshevche/eu-bank/Test
#     - echo "Successfully copied"
#     - cd /home/EUB/dshevche/
#     - rm -rf builds/
#     - cd /home/EUB/dshevche/eu-bank
#     - cp /home/EUB/dshevche/eu-bank/backend-main/.env /home/EUB/dshevche/eu-bank/Test/backend
#     - docker stack deploy -c docker-compose.yml eu
#     - sleep 70
#     - docker service logs --raw eu_payload
#   only:
#     - main
#Test4
