version: '3.8'

services:
  backend:
    image: node:18-alpine
    container_name: test-back
    volumes:
      - .:/home/node/app/
    working_dir: /home/node/app/
    command: sh -c "chmod +x /home/node/app/setup.sh && ./setup.sh"
    depends_on:
      - db
    networks:
      - test-back
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PUSER}
      POSTGRES_PASSWORD: ${PPASS}
      POSTGRES_DB: ${PDB}
    networks:
      - test-back

networks:
  test-back:
    driver: bridge
