import { CollectionConfig } from 'payload/types'

const Offices: CollectionConfig = {
	slug: 'offices',
	labels: {
		singular: 'Отделения',
		plural: 'Отделения',
	},
	access: {
		read: () => true,
	},
	admin: {
		useAsTitle: 'Отделения',
		group: 'Карта банкоматов, терминалов и отделений',
	},
	fields: [
		{
			name: 'latitude',
			label: 'Широта',
			type: 'number',
			required: true,
		},
		{
			name: 'longitude',
			label: 'Долгота',
			type: 'number',
			required: true,
		},
		{
			name: 'address',
			label: 'Адрес',
			type: 'group',
			fields: [
				{
					name: 'labelEn',
					label: 'Название на английском',
					type: 'text',
					required: true,
				},
				{
					name: 'labelRu',
					label: 'Название на русском',
					type: 'text',
					required: true,
				},
				{
					name: 'labelKz',
					label: 'Название на казахском',
					type: 'text',
					required: true,
				},
			],
		},
		{
			name: 'service',
			label: 'Услуга',
			type: 'relationship',
			relationTo: 'service-list',
			required: true,
			hasMany: true,
		},
		{
			name: 'cities',
			type: 'array',
			label: 'Города',
			fields: [
				{
					name: 'city',
					type: 'select',
					label: 'Город',
					options: [
						{
							label: 'Ақсу / Аксу / Aksu',
							value: 'Aksu',
						},
						{
							label: 'Ақтау / Актау / Aktau',
							value: 'Aktau',
						},
						{
							label: 'Ақтөбе / Актобе / Aktobe',
							value: 'Aktobe',
						},
						{
							label: 'Алматы / Алматы / Almaty',
							value: 'Almaty',
						},
						{
							label: 'Алтай / Алтай / Altai',
							value: 'Altai',
						},
						{
							label: 'Арқалық / Аркалык / Arkalyk',
							value: 'Arkalyk',
						},
						{
							label: 'Астана / Астана / Astana',
							value: 'Astana',
						},
						{
							label: 'Атырау / Атырау / Atyrau',
							value: 'Atyrau',
						},
						{
							label: 'Балқаш / Балхаш / Balkhash',
							value: 'Balkhash',
						},
						{
							label: 'Жаңаөзен / Жанаозен / Zhanaozen',
							value: 'Zhanaozen',
						},
						{
							label: 'Жезқазған / Жезказган / Zhezkazgan',
							value: 'Zhezkazgan',
						},
						{
							label: 'Зайсан / Зайсан / Zaisan',
							value: 'Zaisan',
						},
						{
							label: 'Қарағанды / Караганда / Karaganda',
							value: 'Karaganda',
						},
						{
							label: 'Көкшетау / Кокшетау / Kokshetau',
							value: 'Kokshetau',
						},
						{
							label: 'Қостанай / Костанай / Kostanay',
							value: 'Kostanay',
						},
						{
							label: 'Құлсары / Кульсары / Kulsary',
							value: 'Kulsary',
						},
						{
							label: 'Қызылорда / Кызылорда / Kyzylorda',
							value: 'Kyzylorda',
						},
						{
							label: 'Лисаковск / Лисаковск / Lisakovsk',
							value: 'Lisakovsk',
						},
						{
							label: 'Павлодар / Павлодар / Pavlodar',
							value: 'Pavlodar',
						},
						{
							label: 'Петропавл / Петропавловск / Petropavlovsk',
							value: 'Petropavlovsk',
						},
						{
							label: 'Риддер / Риддер / Ridder',
							value: 'Ridder',
						},
						{
							label: 'Рудный / Рудный / Rudny',
							value: 'Rudny',
						},
						{
							label: 'Сарыағаш / Сарыагаш / Saryagash',
							value: 'Saryagash',
						},
						{
							label: 'Семей / Семей / Semei',
							value: 'Semei',
						},
						{
							label: 'Талдықорған / Талдыкорган / Taldykorgan',
							value: 'Taldykorgan',
						},
						{
							label: 'Тараз / Тараз / Taraz',
							value: 'Taraz',
						},
						{
							label: 'Теміртау / Темиртау / Temirtau',
							value: 'Temirtau',
						},
						{
							label: 'Түркістан / Туркестан / Turkestan',
							value: 'Turkestan',
						},
						{
							label: 'Орал / Уральск / Oral',
							value: 'Oral',
						},
						{
							label: 'Өскемен / Усть-Каменогорск / Ust-Kamenogorsk',
							value: 'Ust-Kamenogorsk',
						},
						{
							label: 'Хромтау / Хромтау / Khromtau',
							value: 'Khromtau',
						},
						{
							label: 'Шахтинск / Шахтинск / Shakhtinsk',
							value: 'Shakhtinsk',
						},
						{
							label: 'Шымкент / Шымкент / Shymkent',
							value: 'Shymkent',
						},
						{
							label: 'Екібастұз / Экибастуз / Ekibastuz',
							value: 'Ekibastuz',
						},
					],
				},
			],
		},
		{
			name: 'workingTime',
			label: 'Время работы',
			type: 'group',
			fields: [
				{
					name: 'utc',
					type: 'select',
					label: 'UTC',
					required: true,
					options: [
						{ label: 'UTC-12:00', value: 'UTCm1200' },
						{ label: 'UTC-11:00', value: 'UTCm1100' },
						{ label: 'UTC-10:00', value: 'UTCm1000' },
						{ label: 'UTC-09:30', value: 'UTCm0930' },
						{ label: 'UTC-09:00', value: 'UTCm0900' },
						{ label: 'UTC-08:00', value: 'UTCm0800' },
						{ label: 'UTC-07:00', value: 'UTCm0700' },
						{ label: 'UTC-06:00', value: 'UTCm0600' },
						{ label: 'UTC-05:00', value: 'UTCm0500' },
						{ label: 'UTC-04:00', value: 'UTCm0400' },
						{ label: 'UTC-03:30', value: 'UTCm0330' },
						{ label: 'UTC-03:00', value: 'UTCm0300' },
						{ label: 'UTC-02:00', value: 'UTCm0200' },
						{ label: 'UTC-01:00', value: 'UTCm0100' },
						{ label: 'UTC+00:00', value: 'UTCp0000' },
						{ label: 'UTC+01:00', value: 'UTCp0100' },
						{ label: 'UTC+02:00', value: 'UTCp0200' },
						{ label: 'UTC+03:00', value: 'UTCp0300' },
						{ label: 'UTC+03:30', value: 'UTCp0330' },
						{ label: 'UTC+04:00', value: 'UTCp0400' },
						{ label: 'UTC+04:30', value: 'UTCp0430' },
						{ label: 'UTC+05:00', value: 'UTCp0500' },
						{ label: 'UTC+05:30', value: 'UTCp0530' },
						{ label: 'UTC+05:45', value: 'UTCp0545' },
						{ label: 'UTC+06:00', value: 'UTCp0600' },
						{ label: 'UTC+06:30', value: 'UTCp0630' },
						{ label: 'UTC+07:00', value: 'UTCp0700' },
						{ label: 'UTC+08:00', value: 'UTCp0800' },
						{ label: 'UTC+08:45', value: 'UTCp0845' },
						{ label: 'UTC+09:00', value: 'UTCp0900' },
						{ label: 'UTC+09:30', value: 'UTCp0930' },
						{ label: 'UTC+10:00', value: 'UTCp1000' },
						{ label: 'UTC+10:30', value: 'UTCp1030' },
						{ label: 'UTC+11:00', value: 'UTCp1100' },
						{ label: 'UTC+12:00', value: 'UTCp1200' },
						{ label: 'UTC+12:45', value: 'UTCp1245' },
						{ label: 'UTC+13:00', value: 'UTCp1300' },
						{ label: 'UTC+14:00', value: 'UTCp1400' },
					],
				},
				{
					name: 'startTime',
					type: 'select',
					label: 'Начало рабочего времени',
					required: true,
					options: [
						{ label: '01:00 ночи', value: '01T00' },
						{ label: '01:30 ночи', value: '01T30' },
						{ label: '02:00 ночи', value: '02T00' },
						{ label: '02:30 ночи', value: '02T30' },
						{ label: '03:00 ночи', value: '03T00' },
						{ label: '03:30 ночи', value: '03T30' },
						{ label: '04:00 ночи', value: '04T00' },
						{ label: '04:30 утра', value: '04T30' },
						{ label: '05:00 утра', value: '05T00' },
						{ label: '05:30 утра', value: '05T30' },
						{ label: '06:00 утра', value: '06T00' },
						{ label: '06:30 утра', value: '06T30' },
						{ label: '07:00 утра', value: '07T00' },
						{ label: '07:30 утра', value: '07T30' },
						{ label: '08:00 утра', value: '08T00' },
						{ label: '08:30 утра', value: '08T30' },
						{ label: '09:00 утра', value: '09T00' },
						{ label: '09:30 утра', value: '09T30' },
						{ label: '10:00 утра', value: '10T00' },
						{ label: '10:30 утра', value: '10T30' },
						{ label: '11:00 утра', value: '11T00' },
						{ label: '11:30 утра', value: '11T30' },
						{ label: '12:00 дня', value: '12T00' },
						{ label: '12:30 дня', value: '12T30' },
						{ label: '13:00 дня', value: '13T00' },
						{ label: '13:30 дня', value: '13T30' },
						{ label: '14:00 дня', value: '14T00' },
						{ label: '14:30 дня', value: '14T30' },
						{ label: '15:00 дня', value: '15T00' },
						{ label: '15:30 дня', value: '15T30' },
						{ label: '16:00 дня', value: '16T00' },
						{ label: '16:30 дня', value: '16T30' },
						{ label: '17:00 вечера', value: '17T00' },
						{ label: '17:30 вечера', value: '17T30' },
						{ label: '18:00 вечера', value: '18T00' },
						{ label: '18:30 вечера', value: '18T30' },
						{ label: '19:00 вечера', value: '19T00' },
						{ label: '19:30 вечера', value: '19T30' },
						{ label: '20:00 вечера', value: '20T00' },
						{ label: '20:30 вечера', value: '20T30' },
						{ label: '21:00 вечера', value: '21T00' },
						{ label: '21:30 вечера', value: '21T30' },
						{ label: '22:00 вечера', value: '22T00' },
						{ label: '22:30 вечера', value: '22T30' },
						{ label: '23:00 вечера', value: '23T00' },
						{ label: '23:30 вечера', value: '23T30' },
						{ label: '24:00 вечера', value: '24T00' },
					],
				},
				{
					name: 'endTime',
					type: 'select',
					label: 'Конец рабочего времени',
					required: true,
					options: [
						{ label: '01:00 ночи', value: '01T00' },
						{ label: '01:30 ночи', value: '01T30' },
						{ label: '02:00 ночи', value: '02T00' },
						{ label: '02:30 ночи', value: '02T30' },
						{ label: '03:00 ночи', value: '03T00' },
						{ label: '03:30 ночи', value: '03T30' },
						{ label: '04:00 ночи', value: '04T00' },
						{ label: '04:30 утра', value: '04T30' },
						{ label: '05:00 утра', value: '05T00' },
						{ label: '05:30 утра', value: '05T30' },
						{ label: '06:00 утра', value: '06T00' },
						{ label: '06:30 утра', value: '06T30' },
						{ label: '07:00 утра', value: '07T00' },
						{ label: '07:30 утра', value: '07T30' },
						{ label: '08:00 утра', value: '08T00' },
						{ label: '08:30 утра', value: '08T30' },
						{ label: '09:00 утра', value: '09T00' },
						{ label: '09:30 утра', value: '09T30' },
						{ label: '10:00 утра', value: '10T00' },
						{ label: '10:30 утра', value: '10T30' },
						{ label: '11:00 утра', value: '11T00' },
						{ label: '11:30 утра', value: '11T30' },
						{ label: '12:00 дня', value: '12T00' },
						{ label: '12:30 дня', value: '12T30' },
						{ label: '13:00 дня', value: '13T00' },
						{ label: '13:30 дня', value: '13T30' },
						{ label: '14:00 дня', value: '14T00' },
						{ label: '14:30 дня', value: '14T30' },
						{ label: '15:00 дня', value: '15T00' },
						{ label: '15:30 дня', value: '15T30' },
						{ label: '16:00 дня', value: '16T00' },
						{ label: '16:30 дня', value: '16T30' },
						{ label: '17:00 вечера', value: '17T00' },
						{ label: '17:30 вечера', value: '17T30' },
						{ label: '18:00 вечера', value: '18T00' },
						{ label: '18:30 вечера', value: '18T30' },
						{ label: '19:00 вечера', value: '19T00' },
						{ label: '19:30 вечера', value: '19T30' },
						{ label: '20:00 вечера', value: '20T00' },
						{ label: '20:30 вечера', value: '20T30' },
						{ label: '21:00 вечера', value: '21T00' },
						{ label: '21:30 вечера', value: '21T30' },
						{ label: '22:00 вечера', value: '22T00' },
						{ label: '22:30 вечера', value: '22T30' },
						{ label: '23:00 вечера', value: '23T00' },
						{ label: '23:30 вечера', value: '23T30' },
						{ label: '24:00 вечера', value: '24T00' },
					],
				},
				{
					name: 'days',
					label: 'Дни работы',
					type: 'select',
					options: [
						{ label: 'Каждый день', value: 'everyday' },
						{ label: 'Понедельник - Воскресенье', value: 'monday-sunday' },
						{ label: 'Понедельник - Пятница', value: 'monday-friday' },
						{ label: 'Понедельник - Суббота', value: 'monday-saturday' },
						{ label: 'Вторник - Суббота', value: 'tuesday-saturday' },
						{ label: 'Вторник - Воскресенье', value: 'tuesday-sunday' },
						{ label: 'Среда - Воскресенье', value: 'wednesday-sunday' },
						{ label: 'Среда - Суббота', value: 'wednesday-saturday' },
						{ label: 'Четверг - Воскресенье', value: 'thursday-sunday' },
						{ label: 'Четверг - Суббота', value: 'thursday-saturday' },
						{ label: 'Пятница - Воскресенье', value: 'friday-sunday' },
						{ label: 'Пятница - Суббота', value: 'friday-saturday' },
						{ label: 'Суббота - Воскресенье', value: 'saturday-sunday' },
						{ label: 'Понедельник - Среда', value: 'monday-wednesday' },
						{ label: 'Понедельник - Четверг', value: 'monday-thursday' },
						{ label: 'Понедельник - Вторник', value: 'monday-tuesday' },
						{ label: 'Вторник - Четверг', value: 'tuesday-thursday' },
						{ label: 'Вторник - Среда', value: 'tuesday-wednesday' },
						{ label: 'Среда - Пятница', value: 'wednesday-friday' },
						{ label: 'Среда - Четверг', value: 'wednesday-thursday' },
						{ label: 'Четверг - Пятница', value: 'thursday-friday' },
						{ label: 'Суббота', value: 'saturday' },
						{ label: 'Воскресенье', value: 'sunday' },
						{ label: 'Понедельник', value: 'monday' },
						{ label: 'Вторник', value: 'tuesday' },
						{ label: 'Среда', value: 'wednesday' },
						{ label: 'Четверг', value: 'thursday' },
						{ label: 'Пятница', value: 'friday' },
					],
					required: true,
				},
				{
					name: 'building',
					label: 'Здание',
					type: 'group',
					fields: [
						{
							name: 'labelEn',
							label: 'Название на английском',
							type: 'text',
							required: true,
						},
						{
							name: 'labelRu',
							label: 'Название на русском',
							type: 'text',
							required: true,
						},
						{
							name: 'labelKz',
							label: 'Название на казахском',
							type: 'text',
							required: true,
						},
					],
				},
				{
					name: 'name',
					label: 'Название',
					type: 'group',
					fields: [
						{
							name: 'labelEn',
							label: 'Название на английском',
							type: 'text',
							required: true,
						},
						{
							name: 'labelRu',
							label: 'Название на русском',
							type: 'text',
							required: true,
						},
						{
							name: 'labelKz',
							label: 'Название на казахском',
							type: 'text',
							required: true,
						},
					],
				},
			],
		},
	],
}

export default Offices
